package model.database;

import java.util.List;
import java.util.Random;

/* This model will be converted in the next commits in a JPA model */
public class Book {
    private Integer id;
    private Integer totalPages;
    private String title;
    private String publisher;
    private String genre;
    private List<Page> pages;

    /* *
     * Constructors
     * Constructors can pe autogenerated base on existent data both in Eclipse and Intellij (Alt + insert)
     * */
    public Book(Integer totalPages, String title, String publisher, String genre, List<Page> pages) {
        Random rand = new Random(0);
        this.totalPages = totalPages;
        this.title = title;
        this.publisher = publisher;
        this.genre = genre;
        this.pages = pages;
    }

    public Book(Integer totalPages, String title, String publisher, String genre) {
        Random rand = new Random(0);
        this.id = rand.nextInt();
        this.totalPages = totalPages;
        this.title = title;
        this.publisher = publisher;
        this.genre = genre;
    }

    /* *
     * Getters and setters
     * Getters and setters can pe also autogenerated base on existent data both in Eclipse and Intellij (Alt + insert)
     * */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public List<Page> getPages() {
        return pages;
    }

    public void setPages(List<Page> pages) {
        this.pages = pages;
    }
}
