package model.database;

import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import proto.BookOuterClass;

public class Book {
    private final SimpleIntegerProperty id;
    private final SimpleIntegerProperty totalPages;
    private final SimpleStringProperty title;
    private final SimpleStringProperty publisher;
    private final SimpleStringProperty genre;
    private final SimpleStringProperty author;
    //private List<Page> pages;

    /* *
     * Constructors
     * Constructors can pe autogenerated base on existent data both in Eclipse and Intellij (Alt + insert)
     * */
    public Book(Integer id, Integer totalPages, String title, String publisher, String author, String genre) {
        this.id = new SimpleIntegerProperty(id);
        this.totalPages = new SimpleIntegerProperty(totalPages);
        this.title = new SimpleStringProperty(title);
        this.publisher = new SimpleStringProperty(publisher);
        this.genre = new SimpleStringProperty(genre);
        this.author = new SimpleStringProperty(author);
    }

    public Book(BookOuterClass.Book book) {
        this(book.getId(), book.getTotalPages(), book.getTitle(), book.getPublisher(), book.getAuthor(), book.getGenre().name());
    }

    public Book(Book book) {
        this(book.getId(), book.getTotalPages(), book.getTitle(), book.getPublisher(), book.getAuthor(), book.getGenre());
    }

    /* *
     * Getters and setters
     * Getters and setters can pe also autogenerated base on existent data both in Eclipse and Intellij (Alt + insert)
     * */
    public Integer getId() { return id.get(); }

    public void setId(Integer id) {
        this.id.set(id);
    }

    public Integer getTotalPages() {
        return totalPages.get();
    }

    public void setTotalPages(Integer totalPages) {
        this.totalPages.set(totalPages);
    }

    public String getTitle() {
        return title.get();
    }

    public void setTitle(String title) {
        this.title.set(title);
    }

    public String getPublisher() {
        return publisher.get();
    }

    public void setPublisher(String publisher) {
        this.publisher.set(publisher);
    }

    public String getGenre() {
        return genre.get();
    }

    public void setGenre(String genre) {
        this.genre.set(genre);
    }

    public String getAuthor() {
        return author.get();
    }

    public void setAuthor(String author) {
        this.author.set(author);
    }

/*
    public List<Page> getPages() {
        return pages;
    }

    public void setPages(List<Page> pages) {
        this.pages = pages;
    }
*/

    @Override
    public String toString() {
        return title.get();
    }
}
