package model.database;

import proto.BookOuterClass;

import java.util.List;
import java.util.Random;

/* This model will be converted in the next commits in a JPA model */
public class Book {
    private Integer id;
    private Integer totalPages;
    private String title;
    private String publisher;
    private String genre;
    private String author;
    //private List<Page> pages;


    /* *
     * Constructors
     * Constructors can pe autogenerated base on existent data both in Eclipse and Intellij (Alt + insert)
     * */
    public Book(Integer id, Integer totalPages, String title, String publisher, String author, String genre) {
        this.id = id;
        this.totalPages = totalPages;
        this.title = title;
        this.publisher = publisher;
        this.genre = genre;
        this.author = author;
    }

    public Book(BookOuterClass.Book book) {
        this(book.getId(), book.getTotalPages(), book.getTitle(), book.getPublisher(), book.getAuthor(), book.getGenre().name());
    }

    public Book(Book book) {
        this(book.getId(), book.getTotalPages(), book.getTitle(), book.getPublisher(), book.getAuthor(), book.getGenre());
    }

    /* *
     * Getters and setters
     * Getters and setters can pe also autogenerated base on existent data both in Eclipse and Intellij (Alt + insert)
     * */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

/*
    public List<Page> getPages() {
        return pages;
    }

    public void setPages(List<Page> pages) {
        this.pages = pages;
    }
*/

    @Override
    public String toString() {
        return title;
    }
}
